name: Remove "CUDA CI" Label
'on':
  pull_request_target:
    types:
    - labeled
permissions:
  pull-requests: write
jobs:
  label-remover:
    if: contains(github.event.pull_request.labels.*.name, 'CUDA CI')
    name: Remove "CUDA CI" Label
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: CUDA CI
